site_name: Tutorial for DeepH-pack Workshop 2025
site_url: https://deeph-workshop-tutorial.readthedocs.io/
site_description: "Comprehensive guide for DeepH-pack: from theory to practical applications with Universal Materials Models"

# .mkdocs.yml
docs_dir: ".docs"

theme: 
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

plugins:
  - search

nav:
  - Home: README.md
  - Theoretical Backgrounds: 
      - "Fundamentals": 1.Theoretical_backgrounds.md
  - Getting Started:
      - "Installation Guide": 2.Installation.md
      - "Data Interface Setup": 3.Interface.md
  - Core Workflows:
      - "Model Training": 4.Training.md
      - "Prediction & Inference": 5.Inference.md
  - Advanced Applications:
      - "Universal Materials Models": 6.UMM_odyssey.md

copyright: "Copyright &copy; 2025 DeepH Team"

extra:
  github_url: https://github.com/kYangLi/DeepH-workshop-tutorial
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/kYangLi/DeepH-workshop-tutorial 

extra_css:
  # - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - https://polyfill.io/v3/polyfill.min.js?features=es6

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
